### ISSUE TITLE
Remove .meta files from included .gitignore

### ISSUE THREAD

**Issue by AldeRoberge** [abdelfattahradwan/Fish-Networking-Discovery#10]
![image](https://github.com/abdelfattahradwan/Fish-Networking-Discovery/assets/4276275/0179a025-acdf-4f4d-be36-be90b9619b27)

I've been having troubles with this plugin, scripts were lost when sharing project between team members.

The cause : there is a .gitignore in the project that ignores .meta files.

Solution : Remove .meta from the .gitignore

**Comment by abdelfattahradwan** [comment]
That can't happen, unfortunately. Removing the `.meta` files from the `.gitignore` means they will be included in the plugin's GitHub repository. You should download only the `.cs` files or use the `.unitypackage` that contains only the required files without any extras.

**Comment by AldeRoberge** [comment]
What's the problem with including the .meta files? They are part of any packages.

See the following guide : https://docs.unity3d.com/Manual/CustomPackages.html

I highly recommend you restructure the project using the following guide, this will allow to include as a package (with Unity Package Manager (git) or OpenUPM)

**Comment by abdelfattahradwan** [comment]
> What's the problem with including the .meta files? They are part of any packages.
> 
> See the following guide : https://docs.unity3d.com/Manual/CustomPackages.html
> 
> I highly recommend you restructure the project using the following guide, this will allow to include as a package (with Unity Package Manager (git) or OpenUPM)

Thanks for the link 🙂 I already read that guide.

There are no problems including the `.meta` files (I include them in the pre-packaged release binaries). They are extras in the context of this repository. They don't add or remove any value. Plus, when they change they're extra diff noise 🤷🏻‍♂️

I will look into supporting the Unity Package Manager and OpenUPM soon. Thanks for the suggestion.
