### ISSUE TITLE
Update checks for inputs that start advertising

### ISSUE THREAD

**Issue by AldeRoberge** [abdelfattahradwan/Fish-Networking-Discovery#11]
![image](https://github.com/abdelfattahradwan/Fish-Networking-Discovery/assets/4276275/314c0f95-2a1e-4917-8b73-cd967d1765a8)

This is fine for some kind of quick and dirty debug mode, but this led to our team struggling trying to figure out why the console was spamming with 'Socket Exception : Only one socket use is permitted'. Please disable this feature or only enable it for testing.

**Comment by abdelfattahradwan** [comment]
@AldeRoberge Ah, yes. I will be removing them in the upcoming release.

**Comment by abdelfattahradwan** [comment]
@AldeRoberge this has been in the latest release.
