### ISSUE TITLE
When I query the server broadcast intermittently, the server broadcast disconnects

### ISSUE THREAD

**Issue by ZhaoMCX** [abdelfattahradwan/Fish-Networking-Discovery#13]
After I started the server broadcast, the client searched for the broadcast server by turning on and off the networkDiscovery lookup service every second. After a few times, the server broadcast will be forced to disconnect. I tried to open networkDiscovery and keep it open so that no such issue would arise.
![image](https://github.com/abdelfattahradwan/Fish-Networking-Discovery/assets/78784728/dd80717d-ff6a-4496-a8cb-24f9cc24fda1)

**Comment by abdelfattahradwan** [comment]
@ZhaoMCX Thanks for reporting this. Can you clarify more what you mean by "server broadcast will be forced to disconnect"? When disabling and re-enabling the `NetworkDiscovery` component, the server/client socket should shut down gracefully, also, is that exception thrown by the `NetworkDiscovery` component or something else?

**Comment by ZhaoMCX** [comment]
The sockect error is "Remote host forced closure of an existing connection."，After the NetworkManager create server, I call NetworkDiscovery. AdvertiseServer (). After I call NetworkDiscovery SearchForServers (), call in 1 seconds NetworkDiscovery. StopSearchingOrAdvertising (). Collect the services found during this period. After looping a few times, the error appears.

**Comment by ZhaoMCX** [comment]
Can't broadcast some custom information? I can only get ip and port。

**Comment by abdelfattahradwan** [comment]
> The sockect error is "Remote host forced closure of an existing connection."，After the NetworkManager create server, I call NetworkDiscovery. AdvertiseServer (). After I call NetworkDiscovery SearchForServers (), call in 1 seconds NetworkDiscovery. StopSearchingOrAdvertising (). Collect the services found during this period. After looping a few times, the error appears.

Can you try with intervals shorter and longer than 1 second (e.g. 0.25 seconds, 0.5 seconds, 2 seconds, etc.) to see whether it is related to the timing or not?



> Can't broadcast some custom information? I can only get ip and port。

No, you can not broadcast custom information. You can only get the server IP and port number.
