### ISSUE TITLE
ObjectDisposedException when running NetworkDiscovery.SearchForServersAsync() on Android devices

### ISSUE THREAD

**Issue by khalil-i19** [abdelfattahradwan/Fish-Networking-Discovery#14]
I'm using NetworkDiscovery for room feature on my mobile apps. Previously, I've tested my feature on a single PC device and it works just fine, but when I moved to testing it on an Android device and a PC, sometimes it doesn't immediately found the server, requiring multiple times of advertising server and server search.

The Console displayed an error of ObjectDisposedException when the client starts searching for server. I've checked the script and found that it always break after executing "_clientUdpClient.SendAsync()" method. Is it possible that the UdpClient object got disposed right after the SendAsync method?

![Screenshot 2024-08-27 224522](https://github.com/user-attachments/assets/7e9e5d83-0eec-4cc3-b250-abf2a797aba9)

**Comment by abdelfattahradwan** [comment]
Thanks for bringing this to my attention. I will look into it. Can you test on two computers to see if the issue still occurs there?

**Comment by khalil-i19** [comment]
I have tested it yesterday and the issue still persist..

I'd also like to mention that I've encountered this problem from a few months ago, but at random time the client succeeded in joining the server

**Comment by abdelfattahradwan** [comment]
> I have tested it yesterday and the issue still persist..
> 
> I'd also like to mention that I've encountered this problem from a few months ago, but at random time the client succeeded in joining the server

Gotcha. Thanks for the information. I'll investigate and fix the issue as soon as possible.

**Comment by abdelfattahradwan** [comment]
I just noticed this, but you use an old version. You say, "It always breaks after executing the '_clientUdpClient.SendAsync()' method." In recent versions, `_clientUdpClient` no longer exists.

Please update to the latest version and make sure that you are on the latest version before opening new issues in the future.

**Comment by khalil-i19** [comment]
Hi, I apologize for the late respond. I've checked the script again and it's indeed an old version. Will update it to recent version. Thank you very much for your assistance
