### ISSUE TITLE
Timeout of 0 creates infinite loop and Editor becomes unresponsive

### ISSUE THREAD

**Issue by AldeRoberge** [abdelfattahradwan/Fish-Networking-Discovery#9]
![image](https://github.com/abdelfattahradwan/Fish-Networking-Discovery/assets/4276275/76154d3b-dc93-4b9a-8136-ebc4de3b63ae)

Solution : Do not allow a value of 0 for the timeout.

**Comment by abdelfattahradwan** [comment]
@AldeRoberge I will fix this soon. Thanks for the heads-up.

**Comment by abdelfattahradwan** [comment]
@AldeRoberge This was fixed in the latest release.

**Comment by AldeRoberge** [comment]
Awesome, thanks!
